deploy_production:
  type: deploy
  environment:
    name: staging
    url: blog2
  script:
    - cd /var/www/kirby/mass.memoreview.net && ./update_master.sh
  only:
    - master

deploy_testing:
  type: deploy
  environment:
    name: staging
    url: blog2
  script:
    - cd /var/www/kirby/testmass.memoreview.net && ./update_testing.sh
  only:
    - testing